begin;

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  city text not null,
  source_url text not null,
  privacy text not null,
  address text,
  cuisine text,
  note text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint restaurants_name_not_blank check (btrim(name) <> ''),
  constraint restaurants_city_not_blank check (btrim(city) <> ''),
  constraint restaurants_source_url_not_blank check (btrim(source_url) <> ''),
  constraint restaurants_privacy_check check (privacy in ('private', 'public')),
  constraint restaurants_latitude_range check (
    latitude is null or latitude between -90 and 90
  ),
  constraint restaurants_longitude_range check (
    longitude is null or longitude between -180 and 180
  )
);

create index if not exists restaurants_user_id_idx
  on public.restaurants (user_id);

create index if not exists restaurants_city_idx
  on public.restaurants (city);

create or replace function public.set_restaurants_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_restaurants_updated_at on public.restaurants;

create trigger set_restaurants_updated_at
before update on public.restaurants
for each row
execute function public.set_restaurants_updated_at();

commit;
