begin;

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint collections_name_not_blank check (btrim(name) <> '')
);

create index if not exists collections_user_id_idx
  on public.collections (user_id);

create unique index if not exists collections_user_id_name_idx
  on public.collections (user_id, name);

create or replace function public.set_collections_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_collections_updated_at on public.collections;

create trigger set_collections_updated_at
before update on public.collections
for each row
execute function public.set_collections_updated_at();

create table if not exists public.restaurant_collections (
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  collection_id bigint not null references public.collections (id) on delete cascade,
  primary key (restaurant_id, collection_id)
);

create index if not exists restaurant_collections_collection_id_idx
  on public.restaurant_collections (collection_id);

alter table public.collections enable row level security;
alter table public.restaurant_collections enable row level security;

revoke all on table public.collections from public, anon;
grant select, insert, update, delete on table public.collections to authenticated;

revoke all on sequence public.collections_id_seq from public, anon;
grant usage, select on sequence public.collections_id_seq to authenticated;

revoke all on table public.restaurant_collections from public, anon;
grant select, insert, delete on table public.restaurant_collections to authenticated;

drop policy if exists "Authenticated users can view their own collections"
  on public.collections;

create policy "Authenticated users can view their own collections"
on public.collections
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can insert their own collections"
  on public.collections;

create policy "Authenticated users can insert their own collections"
on public.collections
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can update their own collections"
  on public.collections;

create policy "Authenticated users can update their own collections"
on public.collections
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can delete their own collections"
  on public.collections;

create policy "Authenticated users can delete their own collections"
on public.collections
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can view their own restaurant collections"
  on public.restaurant_collections;

create policy "Authenticated users can view their own restaurant collections"
on public.restaurant_collections
for select
to authenticated
using (
  exists (
    select 1
    from public.collections
    where collections.id = restaurant_collections.collection_id
      and collections.user_id = (select auth.uid())
  )
  and exists (
    select 1
    from public.restaurants
    where restaurants.id = restaurant_collections.restaurant_id
      and restaurants.user_id = (select auth.uid())
  )
);

drop policy if exists "Authenticated users can insert their own restaurant collections"
  on public.restaurant_collections;

create policy "Authenticated users can insert their own restaurant collections"
on public.restaurant_collections
for insert
to authenticated
with check (
  exists (
    select 1
    from public.collections
    where collections.id = restaurant_collections.collection_id
      and collections.user_id = (select auth.uid())
  )
  and exists (
    select 1
    from public.restaurants
    where restaurants.id = restaurant_collections.restaurant_id
      and restaurants.user_id = (select auth.uid())
  )
);

drop policy if exists "Authenticated users can delete their own restaurant collections"
  on public.restaurant_collections;

create policy "Authenticated users can delete their own restaurant collections"
on public.restaurant_collections
for delete
to authenticated
using (
  exists (
    select 1
    from public.collections
    where collections.id = restaurant_collections.collection_id
      and collections.user_id = (select auth.uid())
  )
  and exists (
    select 1
    from public.restaurants
    where restaurants.id = restaurant_collections.restaurant_id
      and restaurants.user_id = (select auth.uid())
  )
);

commit;
